apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-otel-collector
spec:
  type: NodePort
  selector:
    app: otel-collector
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
    - name: debug-http
      port: 8888
      targetPort: 8888
    - name: debug-grpc
      port: 8889
      targetPort: 8889